const defaultAchievements = [
  {
    name: "卡槽空空如也",
    description: "今天也没做任何计划，反正还有明天。",
    condition: "某日无任何任务被放入卡槽",
    points: 3,
    category: "探索型",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "UNKNOWN",
      value: null,
    },
  },
  {
    name: "拖延王者",
    description: "你不是没时间，只是选择再等等。",
    condition: "累计任务失败 5 次",
    points: 5,
    category: "累计型",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_failed_total",
      value: 5,
    },
  },
  {
    name: "第一滴血",
    description: "你删了第一个任务，任务失败并不是终点。",
    condition: "删除卡槽里的一个任务",
    points: 3,
    category: "探索型",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_deleted_single",
      value: 1,
    },
  },
  {
    name: "鸽子终结者",
    description: "你已经连续跳票三天，是在等灵感吗？",
    condition: "连续 3 天未完成任何任务",
    points: 5,
    category: "持续型",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_failed_days_in_row",
      value: 3,
    },
  },
  {
    name: "初来乍到",
    description: "万事起头难，但你已经走出了第一步。",
    condition: "完成 1 个任务",
    points: 5,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 1,
    },
  },
  {
    name: "生活编辑者",
    description: "你像导演一样修改、调整、重构任务，让生活按剧本走。",
    condition: "修改任务内容累计10次",
    points: 10,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_modified_total",
      value: 10,
    },
  },
  {
    name: "勇敢放弃者",
    description: "不是不努力，只是果断删了。",
    condition: "删除任务累计 10 个",
    points: 5,
    category: "累计型",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_deleted_total",
      value: 10,
    },
  },
  {
    name: "删到无影",
    description: "你是极简主义者，删掉了所有任务。",
    condition: "当日内删除卡槽和仓库里的所有任务",
    points: 10,
    category: "探索型",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_deleted_all_in_day",
      value: true,
    },
  },
  {
    name: "绝不拖延",
    description: "提前1小时完成任务，你和拖延症说了再见。",
    condition: "提前1小时完成任务",
    points: 10,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_early_hour",
      value: 1,
    },
  },
  {
    name: "效率机器",
    description: "连续3天不间断，习惯从来都是一点点养成的。",
    condition: "连续 3 天完成任务",
    points: 10,
    category: "持续型",
    isHidden: false,
    reward: {
      exp: 100,
      coins: 200,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 3,
    },
  },
  {
    name: "7日不败",
    description: "一周坚持完成任务，值得奖励一个微笑。",
    condition: "连续 7 天完成任务",
    points: 15,
    category: "持续型",
    isHidden: false,
    reward: {
      exp: 200,
      coins: 400,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 7,
    },
  },
  {
    name: "午夜冲刺者",
    description: "别人梦里你在敲键盘，任务和夜猫子一个都不能少。",
    condition: "晚上 11 点后完成一个任务",
    points: 10,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_after_11pm",
      value: 1,
    },
  },
  {
    name: "任务黑洞",
    description: "失败10个任务，反思是你成长的一部分。",
    condition: "累计失败 10 个任务",
    points: 10,
    category: "累计型",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_failed_total",
      value: 10,
    },
  },
  {
    name: "等级初醒",
    description: "Lv.10，恭喜你走出新手村。",
    condition: "升级到 10 级",
    points: 10,
    category: "成长型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: "道具：开槽卡+1",
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "level_reach",
      value: 10,
    },
  },
  {
    name: "任务合体术",
    description: "你将5个子任务完美融合，安排得明明白白。",
    condition: "创建一个含5个以上子任务的长期任务",
    points: 10,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_created_with_subtasks",
      value: 5,
    },
  },
  {
    name: "新手上路",
    description: "完成10个任务，说明你不是随便试试。",
    condition: "累计完成 10 个任务",
    points: 10,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 100,
      coins: 300,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 10,
    },
  },
  {
    name: "战术大师",
    description: "你不是在完成任务，而是在规划人生。",
    condition: "仓库里同时存在 5 个未装备任务",
    points: 15,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_pending_in_warehouse",
      value: 5,
    },
  },
  {
    name: "从未缺席",
    description: "连续一个月每日登录，你比打卡机还准时。",
    condition: "连续登录 30 天",
    points: 20,
    category: "持续型",
    isHidden: false,
    reward: {
      exp: 400,
      coins: 800,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "login_days_in_row",
      value: 30,
    },
  },
  {
    name: "最后一分钟",
    description: "你总能踩在Deadline上跳舞。",
    condition: "在卡槽任务过期前5分钟内完成任务",
    points: 15,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_last_five_min",
      value: 1,
    },
  },
  {
    name: "习惯成型",
    description: "Lv.20，做事开始得心应手。",
    condition: "升级到 20 级",
    points: 15,
    category: "成长型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: "道具：开槽卡+1",
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "level_reach",
      value: 20,
    },
  },
  {
    name: "月度信仰",
    description: "30天从未放弃，这不只是打卡，这是生活方式。",
    condition: "连续 30 天完成任务",
    points: 25,
    category: "持续型",
    isHidden: false,
    reward: {
      exp: 600,
      coins: 1200,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 30,
    },
  },
  {
    name: "先苦后甜",
    description: "你在一早完成所有任务，是时间管理典范。",
    condition: "早上 8 点前完成卡槽里所有的任务",
    points: 15,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_before_8am",
      value: 1,
    },
  },
  {
    name: "速战速决",
    description: "任务创建后 1 小时内就完成，效率令人发指。",
    condition: "创建并在1小时内完成一个任务",
    points: 15,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_within_hour",
      value: 1,
    },
  },
  {
    name: "一次通过",
    description: "你第一次尝试就完成了长期任务，没有回头路。",
    condition: "完成一个长期任务里所有的子任务",
    points: 20,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_created_with_subtasks",
      value: 5,
    },
  },
  {
    name: "短期专家",
    description: "多次完成短期任务？你是执行力的代名词。",
    condition: "累计完成 20 个短期任务",
    points: 15,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 200,
      coins: 600,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_short_total",
      value: 20,
    },
  },
  {
    name: "任务养成中",
    description: "50次记录，习惯已经开始悄悄扎根。",
    condition: "累计完成 50 个任务",
    points: 20,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 500,
      coins: 1000,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 50,
    },
  },
  {
    name: "百战初成",
    description: "你开始懂得什么叫时间的力量。",
    condition: "累计完成 100 个任务",
    points: 20,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 1000,
      coins: 2000,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 100,
    },
  },
  {
    name: "持久战士",
    description: "长期任务的耐心让你变得格外可靠。",
    condition: "累计完成 10 个长期任务",
    points: 20,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 500,
      coins: 1000,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_long_total",
      value: 10,
    },
  },
  {
    name: "卡槽全开",
    description: "满配短期和长期卡槽，工作空间爆表。",
    condition: "解锁全部 10 个卡槽",
    points: 20,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "card_slot_total",
      value: 10,
    },
  },
  {
    name: "日复一日",
    description: "使用App超过100天，你的习惯已经深植生活。",
    condition: "连续登录 100 天",
    points: 30,
    category: "持续型",
    isHidden: false,
    reward: {
      exp: 1200,
      coins: 2100,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "login_days_total",
      value: 100,
    },
  },
  {
    name: "经验达人",
    description: "累计获得 50,000 经验值，你的努力看得见。",
    condition: "累计经验值达 50,000",
    points: 30,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "exp_total",
      value: 50000,
    },
  },
  {
    name: "自律图腾",
    description: "90天连续不断，你快成自律图腾了。",
    condition: "连续 90 天完成任务",
    points: 40,
    category: "持续型",
    isHidden: false,
    reward: {
      exp: 2500,
      coins: 4000,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 90,
    },
  },
  {
    name: "任务之王",
    description: "累计完成 1000 次任务， 你是时间的驾驭者。",
    condition: "累计完成 1000 个任务",
    points: 40,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 10000,
      coins: 20000,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 1000,
    },
  },
  {
    name: "任务大师",
    description: "Lv.40，身经百战的老手。",
    condition: "升级到 40 级",
    points: 30,
    category: "成长型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: "道具：开槽卡+1",
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "level_reach",
      value: 40,
    },
  },
  {
    name: "已臻化境",
    description: "满级？你已经是这片任务大陆的传说。",
    condition: "升级到 60 级",
    points: 50,
    category: "成长型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: "道具：开槽卡+1",
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "level_reach",
      value: 60,
    },
  },
  {
    name: "稳定如神",
    description: "365 天不缺席，你是任务之神。",
    condition: "连续 365 天完成任务",
    points: 100,
    category: "持续型",
    isHidden: false,
    reward: {
      exp: 10000,
      coins: 20000,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 365,
    },
  },
  {
    name: "成就之神",
    description: "你收集了全部成就，这是任务界的终极荣誉。",
    condition: "解锁全部成就",
    points: 100,
    category: "彩蛋型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: null,
    isEnabled: true,
    logic: {
      type: "achievements_total_unlocked",
      value: "all",
    },
  },
];
export default defaultAchievements;
