const defaultAchievements = [
  {
    name: "第一滴血",
    description: "你删了第一个任务，任务失败并不是终点。",
    condition: "删除卡槽里的一个任务",
    points: 3,
    category: "探索型",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_3.png",
    isEnabled: true,
    logic: {
      type: "task_deleted_total",
      value: 1,
      op: "gte",
    },
  },
  {
    name: "鸽子放飞者",
    description: "你已经连续跳票三天，是在等灵感吗？",
    condition: "连续 3 天未完成任何任务",
    points: 5,
    category: "持续型",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_6.png",
    isEnabled: true,
    logic: {
      type: "task_uncompleted_days_in_row",
      value: 3,
      op: "gte",
    },
  },
  {
    name: "生活编辑者",
    description: "你像导演一样修改、调整、重构任务，让生活按剧本走。",
    condition: "修改任务内容累计10次",
    points: 10,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_13.png",
    isEnabled: true,
    logic: {
      type: "task_edited_total",
      value: 10,
      op: "gte",
    },
  },
  {
    name: "勇敢放弃者",
    description: "不是不努力，只是果断删了。",
    condition: "删除任务累计 10 个",
    points: 5,
    category: "累计型",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_5.png",
    isEnabled: true,
    logic: {
      type: "task_deleted_total",
      value: 10,
      op: "gte",
    },
  },

  {
    name: "效率机器",
    description: "连续3天不间断，习惯从来都是一点点养成的。",
    condition: "连续 3 天完成任务",
    points: 10,
    category: "持续型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 200,
      item: null,
    },
    icon: "default_icon_unlocked_9.png",
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 3,
      op: "gte",
    },
  },
  {
    name: "7日不败",
    description: "一周坚持完成任务，值得奖励一个微笑。",
    condition: "连续 7 天完成任务",
    points: 15,
    category: "持续型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 400,
      item: null,
    },
    icon: "default_icon_unlocked_16.png",
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 7,
      op: "gte",
    },
  },
  {
    name: "午夜冲刺者",
    description: "别人梦里你在敲键盘，任务和夜猫子一个都不能少。",
    condition: "最晚完成任务的时间超过23:00",
    points: 10,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_11.png",
    isEnabled: true,
    logic: {
      type: "task_created_latest_time",
      value: "23:00:00",
      op: "gte",
    },
  },

  {
    name: "等级初醒",
    description: "Lv.10，恭喜你走出新手村。",
    condition: "升级到 10 级",
    points: 10,
    category: "成长型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      task_short_slot: 1,
    },
    icon: "default_icon_unlocked_8.png",
    isEnabled: true,
    logic: {
      type: "level_reach",
      value: 10,
      op: "gte",
    },
  },
  {
    name: "任务合体术",
    description: "你将5个子任务完美融合，安排得明明白白。",
    condition: "创建一个含5个以上子任务的长期任务",
    points: 10,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_12.png",
    isEnabled: true,
    logic: {
      type: "task_created_max_subtasks",
      value: 1,
      op: "gte",
    },
  },
  {
    name: "新手上路",
    description: "完成10个任务，说明你不是随便试试。",
    condition: "累计完成 10 个任务",
    points: 10,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 300,
      item: null,
    },
    icon: "default_icon_unlocked_10.png",
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 10,
      op: "gte",
    },
  },

  {
    name: "最后五分钟",
    description: "你总能踩在Deadline上跳舞。",
    condition: "在卡槽任务过期前5分钟内完成任务",
    points: 15,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_18.png",
    isEnabled: true,
    logic: {
      type: "task_completed_short_longest_duration",
      value: 1435,
      op: "gte",
    },
  },
  {
    name: "习惯成型",
    description: "Lv.20，做事开始得心应手。",
    condition: "升级到 20 级",
    points: 15,
    category: "成长型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      task_long_slot: 1,
    },
    icon: "default_icon_unlocked_14.png",
    isEnabled: true,
    logic: {
      type: "level_reach",
      value: 20,
      op: "gte",
    },
  },
  {
    name: "月度信仰",
    description: "30天从未放弃，这不只是打卡，这是生活方式。",
    condition: "连续 30 天完成任务",
    points: 25,
    category: "持续型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 1200,
      item: null,
    },
    icon: "default_icon_unlocked_26.png",
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 30,
      op: "gte",
    },
  },
  {
    name: "先苦后甜",
    description: "你在一早完成所有任务，是时间管理典范。",
    condition: "最早完成任务的时间在早上8点前",
    points: 15,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_17.png",
    isEnabled: true,
    logic: {
      type: "task_completed_earliest_time",
      value: "08:00:00",
      op: "lt",
    },
  },
  {
    name: "速战速决",
    description: "任务创建后 1 小时内就完成，效率令人发指。",
    condition: "创建并在1小时内完成一个任务",
    points: 15,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_19.png",
    isEnabled: true,
    logic: {
      type: "task_completed_short_shortest_duration",
      value: 60,
      op: "lt",
    },
  },

  {
    name: "短期专家",
    description: "多次完成短期任务？你是执行力的代名词。",
    condition: "累计完成 20 个短期任务",
    points: 15,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 600,
      item: null,
    },
    icon: "default_icon_unlocked_20.png",
    isEnabled: true,
    logic: {
      type: "task_completed_short_total",
      value: 20,
      op: "gte",
    },
  },
  {
    name: "任务养成中",
    description: "50次记录，习惯已经开始悄悄扎根。",
    condition: "累计完成 50 个任务",
    points: 20,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 1000,
      item: null,
    },
    icon: "default_icon_unlocked_23.png",
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 50,
      op: "gte",
    },
  },
  {
    name: "百战初成",
    description: "你开始懂得什么叫时间的力量。",
    condition: "累计完成 100 个任务",
    points: 20,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 2000,
      item: null,
    },
    icon: "default_icon_unlocked_27.png",
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 100,
      op: "gte",
    },
  },
  {
    name: "持久战士",
    description: "长期任务的耐心让你变得格外可靠。",
    condition: "累计完成 10 个长期任务",
    points: 20,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 1000,
      item: null,
    },
    icon: "default_icon_unlocked_27.png",
    isEnabled: true,
    logic: {
      type: "task_completed_long_total",
      value: 10,
      op: "gte",
    },
  },
  {
    name: "卡槽全开",
    description: "满配短期和长期卡槽，工作空间爆表。",
    condition: "解锁全部 10 个卡槽",
    points: 20,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_24.png",
    isEnabled: true,
    logic: {
      type: "card_slot_total",
      value: 10,
      op: "eq",
    },
  },

  {
    name: "经验达人",
    description: "累计获得 50,000 经验值，你的努力看得见。",
    condition: "累计经验值达 50,000",
    points: 30,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_28.png",
    isEnabled: true,
    logic: {
      type: "exp_total",
      value: 50000,
      op: "gte",
    },
  },
  {
    name: "自律图腾",
    description: "90天连续不断，你快成自律图腾了。",
    condition: "连续 90 天完成任务",
    points: 40,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 4000,
      item: null,
    },
    icon: "default_icon_unlocked_30.png",
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 90,
      op: "gte",
    },
  },
  {
    name: "任务之神",
    description: "累计完成 1000 次任务， 你是时间的驾驭者。",
    condition: "累计完成 1000 个任务",
    points: 40,
    category: "累计型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 20000,
      item: null,
    },
    icon: "default_icon_unlocked_31.png",
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 1000,
      op: "gte",
    },
  },
  {
    name: "任务大师",
    description: "Lv.40，身经百战的老手。",
    condition: "升级到 40 级",
    points: 30,
    category: "成长型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      task_short_slot: 1,
      task_long_slot: 1,
    },
    icon: "default_icon_unlocked_29.png",
    isEnabled: true,
    logic: {
      type: "level_reach",
      value: 40,
      op: "gte",
    },
  },
  {
    name: "已臻化境",
    description: "满级？你已经是这片任务大陆的传说。",
    condition: "升级到 60 级",
    points: 50,
    category: "成长型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      task_short_slot: 1,
      task_long_slot: 1,
    },
    icon: "default_icon_unlocked_32.png",
    isEnabled: true,
    logic: {
      type: "level_reach",
      value: 60,
      op: "gte",
    },
  },
  {
    name: "稳定如神",
    description: "365 天不缺席，你是任务之神。",
    condition: "连续 365 天完成任务",
    points: 100,
    category: "持续型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 20000,
      item: null,
    },
    icon: "default_icon_unlocked_33.png",
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 365,
      op: "gte",
    },
  },
  {
    name: "卡片收纳狂",
    description: "你囤下了整整一打空白卡，是准备开店了吗？",
    condition: "最高持有10张以上的白卡",
    points: 10,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_7.png",
    isEnabled: true,
    logic: {
      type: "blank_card_max_held",
      value: 10,
      op: "gte",
    },
  },

  {
    name: "腰包鼓了鼓	",
    description: "你身上开始有点份量了，但真正的富有还在远方。",
    condition: "最高持有3000金币以上",
    points: 20,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_21.png",
    isEnabled: true,
    logic: {
      type: "max_gold",
      value: 3000,
      op: "gte",
    },
  },

  {
    name: "黄金蓄能者",
    description: "你用行动证明了储蓄是一种力量，金币在你手中闪闪发光。",
    condition: "最高持有10000金币以上",
    points: 25,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_25.png",
    isEnabled: true,
    logic: {
      type: "max_gold",
      value: 10000,
      op: "gte",
    },
  },

  {
    name: "奇迹调度者",
    description: "你收集了十张特殊卡，计划背后藏着力量与野心。",
    condition: "最高持有10张特殊卡",
    points: 15,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_15.png",
    isEnabled: true,
    logic: {
      type: "special_card_max_held",
      value: 10,
      op: "gte",
    },
  },

  {
    name: "晨光起步者",
    description: "当别人还在沉睡时，你已迈出了高效的一步。",
    condition: "最早创建任务的时间小于08:00:00",
    points: 3,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_1.png",
    isEnabled: true,
    logic: {
      type: "task_created_earliest_time",
      value: "08:00:00",
      op: "lt",
    },
  },

  {
    name: "熬夜生产者",
    description: "任务不等人，灵感不等天亮",
    condition: "最晚创建任务的时间超过23:00",
    points: 3,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_2.png",
    isEnabled: true,
    logic: {
      type: "task_created_latest_time",
      value: "23:00:00",
      op: "gte",
    },
  },

  {
    name: "成就之神",
    description: "你收集了全部成就，这是任务界的终极荣誉。",
    condition: "解锁全部成就",
    points: 100,
    category: "彩蛋型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_34.png",
    isEnabled: true,
    logic: {
      type: "achievements_total_unlocked",
      value: "33",
      op: "gte",
    },
  },
  {
    name: "初来乍到",
    description: "万事起头难，但你已经走出了第一步。",
    condition: "完成 1 个任务",
    points: 5,
    category: "探索型",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      item: null,
    },
    icon: "default_icon_unlocked_4.png",
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 1,
      op: "gte",
    },
  },
];
export default defaultAchievements;
