const defaultAchievements = [
  {
    name: "First Blood",
    description:
      "You reached the bottom and saw the truth—your ultimate achievement.",
    condition: "Delete a task from the slot",
    points: 3,
    category: "Exploration",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_3.png",
    isEnabled: true,
    logic: {
      type: "task_deleted_total",
      value: 1,
      op: "gte",
    },
  },
  {
    name: "Chronic Procrastinator",
    description:
      "You have postponed tasks for three consecutive days. Waiting for inspiration?",
    condition: "Fail to complete any task for 3 consecutive days",
    points: 5,
    category: "Continuous",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_6.png",
    isEnabled: true,
    logic: {
      type: "task_uncompleted_days_in_row",
      value: 3,
      op: "gte",
    },
  },
  {
    name: "Life Editor",
    description:
      "You edit, adjust, and restructure tasks like a director, making life follow the script.",
    condition: "Edit task content 10 times in total",
    points: 10,
    category: "Cumulative",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_13.png",
    isEnabled: true,
    logic: {
      type: "task_edited_total",
      value: 10,
      op: "gte",
    },
  },
  {
    name: "Bold Quitter",
    description: "It's not about not trying, it's about decisively deleting.",
    condition: "Delete 10 tasks in total",
    points: 5,
    category: "Cumulative",
    isHidden: true,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_5.png",
    isEnabled: true,
    logic: {
      type: "task_deleted_total",
      value: 10,
      op: "gte",
    },
  },

  {
    name: "Productivity Machine",
    description:
      "Three days of uninterrupted work. Habits are built step by step.",
    condition: "Complete tasks for 3 consecutive days",
    points: 10,
    category: "Continuous",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 200,
    },
    icon: "default_icon_unlocked_9.png",
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 3,
      op: "gte",
    },
  },
  {
    name: "Unbeaten for 7 Days",
    description: "Complete tasks for a week straight. You deserve a smile.",
    condition: "Complete tasks for 7 consecutive days",
    points: 15,
    category: "Continuous",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 400,
    },
    icon: "default_icon_unlocked_16.png",
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 7,
      op: "gte",
    },
  },
  {
    name: "Midnight Sprinter",
    description:
      "While others dream, you're typing away. Tasks and night owls can't be missed.",
    condition: "Complete a task after 23:00",
    points: 10,
    category: "Exploration",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_11.png",
    isEnabled: true,
    logic: {
      type: "task_created_latest_time",
      value: "23:00:00",
      op: "gte",
    },
  },

  {
    name: "Awakening Level",
    description: "Lv.10, congratulations on leaving the beginner's village.",
    condition: "Reach level 10",
    points: 10,
    category: "Growth",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      task_short_slot: 1,
    },
    icon: "default_icon_unlocked_8.png",
    isEnabled: true,
    logic: {
      type: "level_reach",
      value: 10,
      op: "gte",
    },
  },
  {
    name: "Task Fusion",
    description:
      "You perfectly merged 5 subtasks, making everything crystal clear.",
    condition: "Create a long-term task with more than 5 subtasks",
    points: 10,
    category: "Exploration",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_12.png",
    isEnabled: true,
    logic: {
      type: "task_created_max_subtasks",
      value: 1,
      op: "gte",
    },
  },
  {
    name: "Rookie on the Road",
    description: "Complete 10 tasks, proving you're not just trying it out.",
    condition: "Complete 10 tasks in total",
    points: 10,
    category: "Cumulative",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 300,
    },
    icon: "default_icon_unlocked_10.png",
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 10,
      op: "gte",
    },
  },

  {
    name: "Last Five Minutes",
    description: "You always manage to dance on the edge of the deadline.",
    condition: "Complete a task within 5 minutes before it expires in the slot",
    points: 15,
    category: "Exploration",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_18.png",
    isEnabled: true,
    logic: {
      type: "task_completed_short_longest_duration",
      value: 1435,
      op: "gte",
    },
  },
  {
    name: "Habit Formed",
    description: "Lv.20, you're starting to get the hang of things.",
    condition: "Reach level 20",
    points: 15,
    category: "Growth",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      task_long_slot: 1,
    },
    icon: "default_icon_unlocked_14.png",
    isEnabled: true,
    logic: {
      type: "level_reach",
      value: 20,
      op: "gte",
    },
  },
  {
    name: "Monthly Devotion",
    description:
      "30 days without giving up. This is more than a habit, it's a lifestyle.",
    condition: "Complete tasks for 30 consecutive days",
    points: 25,
    category: "Continuous",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 1200,
    },
    icon: "default_icon_unlocked_26.png",
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 30,
      op: "gte",
    },
  },
  {
    name: "Early Riser",
    description:
      "You completed all your tasks early in the morning. A true time management expert.",
    condition: "Complete all tasks before 8:00 AM",
    points: 15,
    category: "Exploration",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_17.png",
    isEnabled: true,
    logic: {
      type: "task_completed_earliest_time",
      value: "08:00:00",
      op: "lt",
    },
  },
  {
    name: "Swift Executor",
    description:
      "You completed a task within 1 hour of creating it. Efficiency at its peak.",
    condition: "Create and complete a task within 1 hour",
    points: 15,
    category: "Exploration",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_19.png",
    isEnabled: true,
    logic: {
      type: "task_completed_short_shortest_duration",
      value: 60,
      op: "lt",
    },
  },

  {
    name: "Short Task Specialist",
    description:
      "You completed multiple short-term tasks. You're the definition of execution power.",
    condition: "Complete 20 short-term tasks in total",
    points: 1,
    category: "Cumulative",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 600,
    },
    icon: "default_icon_unlocked_20.png",
    isEnabled: true,
    logic: {
      type: "task_completed_short_total",
      value: 20,
      op: "gte",
    },
  },
  {
    name: "Task Habit Developer",
    description: "50 tasks completed. A habit is quietly taking root.",
    condition: "Complete 50 tasks in total",
    points: 20,
    category: "Cumulative",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 1000,
    },
    icon: "default_icon_unlocked_23.png",
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 50,
      op: "gte",
    },
  },
  {
    name: "Veteran in the Making",
    description: "You are beginning to understand the power of time.",
    condition: "Complete 100 tasks in total",
    points: 20,
    category: "Cumulative",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 2000,
    },
    icon: "default_icon_unlocked_27.png",
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 100,
      op: "gte",
    },
  },
  {
    name: "Long-term Warrior",
    description:
      "Your patience with long-term tasks makes you exceptionally reliable.",
    condition: "Complete 10 long-term tasks in total",
    points: 20,
    category: "Cumulative",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 1000,
    },
    icon: "default_icon_unlocked_27.png",
    isEnabled: true,
    logic: {
      type: "task_completed_long_total",
      value: 10,
      op: "gte",
    },
  },
  {
    name: "Full Slot Power",
    description:
      "Fully equipped with short-term and long-term slots. Your workspace is maxed out.",
    condition: "Unlock all 10 slots",
    points: 20,
    category: "Cumulative",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_24.png",
    isEnabled: true,
    logic: {
      type: "card_slot_total",
      value: 10,
      op: "eq",
    },
  },

  {
    name: "XP Master",
    description:
      "Accumulate 50,000 experience points. Your efforts are visible.",
    condition: "Accumulate 50,000 experience points",
    points: 30,
    category: "Cumulative",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_28.png",
    isEnabled: true,
    logic: {
      type: "exp_total",
      value: 50000,
      op: "gte",
    },
  },
  {
    name: "Totem of Discipline",
    description:
      "90 days of continuous effort. You are becoming a totem of discipline.",
    condition: "Complete tasks for 90 consecutive days",
    points: 40,
    category: "Cumulative",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 4000,
    },
    icon: "default_icon_unlocked_30.png",
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 90,
      op: "gte",
    },
  },
  {
    name: "Task Deity",
    description: "Complete 1,000 tasks in total. You are the master of time.",
    condition: "Complete 1,000 tasks in total",
    points: 40,
    category: "Cumulative",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 20000,
    },
    icon: "default_icon_unlocked_31.png",
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 1000,
      op: "gte",
    },
  },
  {
    name: "Task Master",
    description: "Lv.40, a seasoned veteran.",
    condition: "Reach level 40",
    points: 30,
    category: "Growth",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      task_short_slot: 1,
      task_long_slot: 1,
    },
    icon: "default_icon_unlocked_29.png",
    isEnabled: true,
    logic: {
      type: "level_reach",
      value: 40,
      op: "gte",
    },
  },
  {
    name: "Legendary Level",
    description: "Max level? You are now a legend in the task world.",
    condition: "Reach level 60",
    points: 50,
    category: "Growth",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
      task_short_slot: 1,
      task_long_slot: 1,
    },
    icon: "default_icon_unlocked_32.png",
    isEnabled: true,
    logic: {
      type: "level_reach",
      value: 60,
      op: "gte",
    },
  },
  {
    name: "Steadfast as a God",
    description: "365 days without missing a task. You are the god of tasks.",
    condition: "Complete tasks for 365 consecutive days",
    points: 100,
    category: "Continuous",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 20000,
    },
    icon: "default_icon_unlocked_33.png",
    isEnabled: true,
    logic: {
      type: "task_completed_days_in_row",
      value: 365,
      op: "gte",
    },
  },
  {
    name: "Card Hoarder",
    description:
      "You hoarded a dozen blank cards. Are you planning to open a shop?",
    condition: "Hold more than 10 blank cards at once",
    points: 10,
    category: "Exploration",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_7.png",
    isEnabled: true,
    logic: {
      type: "blank_card_max_held",
      value: 10,
      op: "gte",
    },
  },

  {
    name: "Wallet Gained Weight",
    description:
      "Your wallet is getting heavier, but true wealth is still far away.",
    condition: "Hold more than 3,000 coins at once",
    points: 20,
    category: "Exploration",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_21.png",
    isEnabled: true,
    logic: {
      type: "max_gold",
      value: 3000,
      op: "gte",
    },
  },

  {
    name: "Gold Hoarder",
    description:
      "You proved that saving is a strength. Coins shine in your hands.",
    condition: "Hold more than 10,000 coins at once",
    points: 25,
    category: "Exploration",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_25.png",
    isEnabled: true,
    logic: {
      type: "max_gold",
      value: 10000,
      op: "gte",
    },
  },

  {
    name: "Miracle Planner",
    description:
      "You collected 10 special cards. Behind the plan lies power and ambition.",
    condition: "Hold 10 special cards at once",
    points: 15,
    category: "Exploration",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_15.png",
    isEnabled: true,
    logic: {
      type: "special_card_max_held",
      value: 10,
      op: "gte",
    },
  },

  {
    name: "Dawn Starter",
    description:
      "While others are still asleep, you've taken the first efficient step.",
    condition: "Create a task before 08:00 AM",
    points: 3,
    category: "Exploration",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_1.png",
    isEnabled: true,
    logic: {
      type: "task_created_earliest_time",
      value: "08:00:00",
      op: "lt",
    },
  },

  {
    name: "Late-night Creator",
    description: "Tasks wait for no one, and inspiration waits for no sunrise.",
    condition: "Create a task after 23:00",
    points: 3,
    category: "Exploration",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_2.png",
    isEnabled: true,
    logic: {
      type: "task_created_latest_time",
      value: "23:00:00",
      op: "gte",
    },
  },

  {
    name: "Achievement God",
    description:
      "You unlocked all achievements. This is the ultimate honor in the task world.",
    condition: "Unlock all achievements",
    points: 100,
    category: "Easter_Egg",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_34.png",
    isEnabled: true,
    logic: {
      type: "achievements_total_unlocked",
      value: 40,
      op: "gte",
    },
  },
  {
    name: "Newcomer",
    description:
      "The first step is always the hardest, but you've already taken it.",
    condition: "Complete 1 task",
    points: 5,
    category: "Exploration",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_4.png",
    isEnabled: true,
    logic: {
      type: "task_completed_total",
      value: 1,
      op: "gte",
    },
  },
  {
    name: "Step into the Maze",
    description:
      "Your first exploration of the maze marks the beginning of your adventure.",
    condition: "Reach a maximum maze exploration depth of 10 levels",
    points: 10,
    category: "Growth",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_35.png",
    isEnabled: true,
    logic: {
      type: "max_maze_level",
      value: 10,
      op: "gte",
    },
  },
  {
    name: "Lost Explorer",
    description:
      "You've ventured deeper into the maze, still carrying confusion.",
    condition: "Reach a maximum maze exploration depth of 20 levels",
    points: 20,
    category: "Growth",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_36.png",
    isEnabled: true,
    logic: {
      type: "max_maze_level",
      value: 20,
      op: "gte",
    },
  },
  {
    name: "Name of the Brave",
    description: "You are now called 'The Challenger.'",
    condition: "Reach a maximum maze exploration depth of 30 levels",
    points: 30,
    category: "Growth",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_37.png",
    isEnabled: true,
    logic: {
      type: "max_maze_level",
      value: 30,
      op: "gte",
    },
  },
  {
    name: "Abyss Conqueror",
    description:
      "You've entered the higher levels of the maze, and your strength is growing significantly.",
    condition: "Reach a maximum maze exploration depth of 40 levels",
    points: 40,
    category: "Growth",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_38.png",
    isEnabled: true,
    logic: {
      type: "max_maze_level",
      value: 40,
      op: "gte",
    },
  },
  {
    name: "Blade of the Boundary",
    description:
      "Touching the truth of the maze means breaking limits and approaching the extreme.",
    condition: "Reach a maximum maze exploration depth of 50 levels",
    points: 50,
    category: "Growth",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_39.png",
    isEnabled: true,
    logic: {
      type: "max_maze_level",
      value: 50,
      op: "gte",
    },
  },
  {
    name: "Maze Overlord",
    description:
      "Reaching the deepest part of the maze, you witnessed the truth of the world. This is your ultimate achievement.",
    condition: "Reach a maximum maze exploration depth of 60 levels",
    points: 60,
    category: "Growth",
    isHidden: false,
    reward: {
      exp: 0,
      coins: 0,
    },
    icon: "default_icon_unlocked_40.png",
    isEnabled: true,
    logic: {
      type: "max_maze_level",
      value: 60,
      op: "gte",
    },
  },
];
export default defaultAchievements;
