const seedItems = [
  // ⚔️ Weapons
  new WeaponItem({
    name: "Iron Blade",
    type: "weapon",
    price: 120,
    icon: "icon-sword",
    description: "A basic iron sword, suitable for novice warriors.",
    weaponType: "sword",
    stats: { attack: 12, magicPower: 0, critRate: 0.05, accuracy: 0.9 },
    slot: "mainHand",
    allowedClasses: ["warrior"],
  }),
  new WeaponItem({
    name: "Apprentice’s Wand",
    type: "weapon",
    price: 140,
    icon: "icon-staff",
    description: "A magic wand suitable for beginners, imbued with faint magical power.",
    weaponType: "staff",
    stats: { attack: 3, magicPower: 15, critRate: 0.02, accuracy: 0.95 },
    slot: "mainHand",
    allowedClasses: ["mage"],
  }),
  new WeaponItem({
    name: "Precision Shortbow",
    type: "weapon",
    price: 135,
    icon: "icon-bow",
    description: "A nimble shortbow, enhancing accuracy and critical hit rate.",
    weaponType: "bow",
    stats: { attack: 9, magicPower: 0, critRate: 0.12, accuracy: 0.97 },
    slot: "mainHand",
    allowedClasses: ["archer"],
  }),

  // 🛡️ Armors
  new ArmorItem({
    name: "Leather Armor",
    type: "armor",
    price: 90,
    icon: "icon-leather",
    description: "Light leather armor, ideal for agile classes.",
    armorType: "leather",
    stats: { defense: 5, magicResist: 2, evasion: 0.05 },
    slot: "chest",
    allowedClasses: ["rogue", "archer"],
  }),
  new ArmorItem({
    name: "Apprentice’s Robe",
    type: "armor",
    price: 100,
    icon: "icon-cloth",
    description: "A mage-exclusive robe that boosts magic resistance and evasion.",
    armorType: "cloth",
    stats: { defense: 2, magicResist: 5, evasion: 0.1 },
    slot: "chest",
    allowedClasses: ["mage"],
  }),
  new ArmorItem({
    name: "Iron Round Shield",
    type: "armor",
    price: 110,
    icon: "icon-shield",
    description: "A sturdy round shield that increases physical defense.",
    armorType: "shield",
    stats: { defense: 8, magicResist: 1, evasion: 0.02 },
    slot: "offHand",
    allowedClasses: ["warrior"],
  }),

  // 💊 Consumables
  new ConsumableItem({
    name: "Small Healing Potion",
    type: "consumable",
    price: 50,
    icon: "icon-heal",
    description: "Automatically restore 30 HP when your health falls below 30%.",
    effect: "heal",
    potency: 30,
    trigger: "onLowHp",
  }),
  new ConsumableItem({
    name: "Attack Power Booster",
    type: "consumable",
    price: 65,
    icon: "icon-buff-attack",
    description: "Increase attack power by 10% during this exploration.",
    effect: "buff-attack",
    potency: 0.1,
    trigger: "onBattleStart",
  }),

  // 🔮 Materials
  new MaterialItem({
    name: "Slime Gel",
    type: "material",
    icon: "icon-slime",
    description: "A material extracted from slimes, commonly used for basic alchemy.",
    rarity: "common",
    source: "slime",
  }),
  new MaterialItem({
    name: "Shadow Crystal",
    type: "material",
    icon: "icon-crystal",
    description: "A rare magical crystal harvested from the Shadow Realm.",
    rarity: "rare",
    source: "ghost",
  }),
];
